name: The Base
description: >
  You stand at the base of the mountain. It's imposing and unmovable nature scorne your brevity. It is open, strong, confident. Who are you to conquer it?
coverImage: /images/locations/city.png
