name: The Base
description: >
  This route is unknown to many and has the potential of being dangerous, but with much
  reward from witnessing the stunning view and going somewhere where no one else has gone
  before. You look ahead, seeing a great canyon of tall rock formations with a path
  running through it. You enter in.
coverImage: https://d1lrsvyr5nwi6q.cloudfront.net/locations/LOE-Base.png
