export interface Encounter {
	coverImageUrl?: string;
	description: string;
	choices?: EncounterChoice[];
	isBoundToLocation?: boolean;

	// Auto generated by api
	encounterId: string;
}

export interface EncounterChoice {
	choiceText: string;
	result: string;
	buttonBackgroundColor?: string;
}
