import { createContext, useContext } from 'react';
import { ITheme } from '../../types/ITheme';
import { defaultTheme } from './default-theme';
import { IPartialTheme } from '../../types/IPartialTheme';
import { darken, lighten } from 'polished';

const ThemeContext = createContext<IPartialTheme>({});

export const ThemeProvider = ThemeContext.Provider;

export function useTheme(): ITheme {
	const partialTheme = useContext(ThemeContext);

	const autoGenerated: IPartialTheme = {};
	if (partialTheme.buttonBackground && !partialTheme.buttonHoverBackground) {
		autoGenerated.buttonHoverBackground = darken(0.1, partialTheme.buttonBackground);
	}

	if (partialTheme.buttonBackground && !partialTheme.buttonDisabledBackground) {
		autoGenerated.buttonDisabledBackground = lighten(0.2, partialTheme.buttonBackground);
	}

	return {
		...defaultTheme,
		...autoGenerated,
		...partialTheme,
	};
}
