import { createContext, useContext } from 'react';
import { ITheme } from '../../types/ITheme';
import { defaultTheme } from './default-theme';
import { IPartialTheme } from '../../types/IPartialTheme';
import { darken } from 'polished';

const ThemeContext = createContext<IPartialTheme>({});

export const ThemeProvider = ThemeContext.Provider;

export function useTheme(): ITheme {
	const partialTheme = useContext(ThemeContext);

	const autoGeneratedHovers: IPartialTheme = {};
	if (partialTheme.buttonBackground && !partialTheme.buttonHoverBackground) {
		autoGeneratedHovers.buttonHoverBackground = darken(0.1, partialTheme.buttonBackground);
	}

	return {
		...defaultTheme,
		...autoGeneratedHovers,
		...partialTheme,
	};
}
