name: Build

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Write service account credentials
        run: echo "$GOOGLE_KEY" > ./googleCreds.json
        env:
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}

      - name: Write AWS credentials
        run: echo "$AWS_CREDENTIALS" > ./awsCreds.json
        env:
          AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}

      - name: Deploy
        uses: josephdangerstewart/configuration/actions/deploy-node-app@master
        with:
          ssh_private_key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          deployment_host: 64.227.48.74
